---
title: "R Markdown and Leaflet"
author: "Riki Uusoksa"
date: "May 5th, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(leaflet)
espooIcon <- makeIcon(iconUrl = './espoo.png', iconWidth = 40, iconHeight = 40, iconAnchorX = 20, iconAnchorY = 20)

helsinkiIcon <- makeIcon(iconUrl = './helsinki.png', iconWidth = 40, iconHeight = 40, iconAnchorX = 20, iconAnchorY = 20)

vantaaIcon <- makeIcon(iconUrl = './vantaa.png', iconWidth = 40, iconHeight = 40, iconAnchorX = 20, iconAnchorY = 20)

kauniainenIcon <- makeIcon(iconUrl = './kauniainen.png', iconWidth = 40, iconHeight = 40, iconAnchorX = 20, iconAnchorY = 20)

icons <- iconList(helsinkiIcon, espooIcon, vantaaIcon, kauniainenIcon)

df <- data.frame(names = c('Helsinki', 'Espoo', 'Vantaa', 'Kauniainen'),
                 pop = c(629512, 270416, 215813, 9395),
                 dens = c(2945.09, 866, 905.37, 1597.79),
                 lat = c(60.170833, 60.205556, 60.294444, 60.216667),
                 lng = c(24.9375, 24.655556, 25.040278, 24.733333),
                 col = c('red', 'black', 'green', 'magenta'))

df %>%
  leaflet() %>%
  addTiles() %>%
  addCircles(col = df$col, weight = 5, radius = (df$pop / df$dens) * 30) %>%
  addMarkers(label = df$names, icon = icons) %>%
  fitBounds(lng1 = min(df$lng), lng2 = max(df$lng), lat1 = min(df$lat)-0.03, lat2 = max(df$lat)+0.03)
```

#### Explanation

The circles have a radius defined by the population divided by population density (so area of the city) and the markers are each city's Coat of Arms that are located in the middle of the city. As you can see, Kauniainen is a city that's surrounded by Espoo.